### ISSUE TITLE
AtomicProperty javadoc contains removed method from DynamicProperty 

### ISSUE THREAD

**Issue by KazankovMarch** [ru-fix/dynamic-property#24]
DynamicProperty#addAndCallListener(..) was removed from DynamicProperty interface

![Screenshot from 2020-05-21 17-02-10](https://user-images.githubusercontent.com/28933068/82566691-f82e6580-9b84-11ea-8c4e-bbb21d690734.png)

**Comment by swarmshine** [comment]
docs are fixed
